#!/usr/bin/env python
#
# Copyright (c) 2020 Volodymyr Flonts <flyonts@gmail.com>
#
# License MIT https://opensource.org/licenses/MIT
#
from __future__ import print_function
import os
import sys
import pyotp
import pyqrcode


def perror(msg, *args, **kwargs):
    kwargs['file'] = sys.stderr
    print("Error:", msg, *args, **kwargs)


def main():
    keyfile = "~/.google_authenticator"
    keysize = 26

    if "-h" in sys.argv or "--help" in sys.argv:
        print("usage: optcreate [keyfile [size]]")
        print("default keyfile", keyfile)
        return 100

    if "--version" in sys.argv:
        print("otpcreate v0.3 beta")
        return 101

    if len(sys.argv) > 1 and sys.argv[1] != "-":
        keyfile = sys.argv[1]

    if len(sys.argv) > 2:
        keysize = int(sys.argv[2])

    if keyfile.startswith("~/"):
        homedir = os.environ.get("HOME", ".")
        keyfile = homedir + keyfile[1:]

    try:
        kfstat = os.stat(keyfile)
    except OSError:
        kdirst = os.stat(os.path.dirname(keyfile))
        kfstat = None

    if kfstat:
        perror("keyfile exists", keyfile)
        return 201

    if kdirst.st_mode & 0o022 != 0:
        perror("bad keydir mode", keyfile)
        return 203

    if 16 > keysize > 100:
        perror("bad key size", keysize)
        return 204

    secret = pyotp.random_base32(keysize)

    try:
        with open(keyfile, "wt") as fp:
            os.chmod(keyfile, 0o400)
            fp.write(secret + "\n")
    except OSError:
        perror("keyfile write error", keyfile)
        return 205

    totp = pyotp.TOTP(secret)
    name = os.environ.get("USER", "-")
    host = os.uname()[1]

    uri = totp.provisioning_uri(name, host)
    qr = pyqrcode.create(uri)

    print(qr.terminal(quiet_zone=1))

    print("Scan QR code or copy-paste code: ", secret, end="\n\n")
    print("or open this link on your phone: ", uri, end="\n\n")


if __name__ == '__main__':
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        perror("aborted")
        sys.exit(10)
    except Exception as exc:
        perror(str(exc))
        sys.exit(20)
